version: "3.8"

services:
  teamcity-server:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - teamcity_server_data:/data/teamcity_server/datadir
      - teamcity_server_logs:/opt/teamcity/logs
    restart: unless-stopped

  teamcity-agent:
    image: jetbrains/teamcity-agent
    container_name: teamcity-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
    depends_on:
      - teamcity-server
    volumes:
      - teamcity_agent_conf:/data/teamcity_agent/conf
    restart: unless-stopped
  postgres:
    image: postgres:14
    container_name: teamcity-postgres
    environment:
      POSTGRES_DB: teamcity
      POSTGRES_USER: teamcity
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonarpass
    depends_on:
      - sonar-postgres
    restart: unless-stopped

  sonar-postgres:
    image: postgres:14
    container_name: sonar-postgres
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpass
    volumes:
      - sonar_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  teamcity_server_data:
  teamcity_server_logs:
  teamcity_agent_conf:
  pgdata:
  sonar_pgdata: